#!/bin/bash
# omarchy-zen — Zen Browser theme integration for Omarchy
# https://github.com/mehexi/omarchy-zen
#
# Automatically syncs your active Omarchy theme to Zen Browser's userChrome.css
# and hooks into omarchy-theme-set-browser so themes update on every switch.

set -e

OMARCHY_BIN="$HOME/.local/share/omarchy/bin"
ZEN_CONFIG="$HOME/.config/zen"
SCRIPT_NAME="omarchy-theme-set-zen"

echo "→ Installing omarchy-zen..."

# ── 1. Find Zen config + profile ────────────────────────────────────────────────────────
for CANDIDATE in "$HOME/.config/zen" "$HOME/.zen"; do
  if [[ -f "$CANDIDATE/installs.ini" ]]; then
    ZEN_CONFIG="$CANDIDATE"
  fi
done

if [[ -z  "$ZEN_CONFIG" ]]; then
  echo "x Could not find Zen installs.ini"
  echo "  Checked: $HOME/.config/zen and $HOME/.zen"
  exit 1
fi

ZEN_PROFILE=$(grep 'Default=' "$ZEN_CONFIG/installs.ini" 2>/dev/null \
  | head -1 | cut -d= -f2)

if [[ -z "$ZEN_PROFILE" ]]; then
  echo "✗ Could not detect Zen profile from installs.ini"
  echo "  Please set ZEN_PROFILE manually in $OMARCHY_BIN/$SCRIPT_NAME"
  exit 1
fi

ZEN_CHROME_DIR="$ZEN_CONFIG/$ZEN_PROFILE/chrome"
mkdir -p "$ZEN_CHROME_DIR"
echo "✓ Zen profile: $ZEN_PROFILE"

# ── 2. Enable userChrome.css in Zen ───────────────────────────────────────────
PREFS_JS="$ZEN_CONFIG/$ZEN_PROFILE/prefs.js"
if [[ -f "$PREFS_JS" ]]; then
  # Remove any existing entry first to avoid duplicates
  sed -i '/toolkit.legacyUserProfileCustomizations/d' "$PREFS_JS"
  echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$PREFS_JS"
  echo "✓ Enabled userChrome.css in prefs.js"
else
  echo "⚠ prefs.js not found — open Zen once, then re-run this installer"
fi

# ── 3. Write the theme script ──────────────────────────────────────────────────
cat > "$OMARCHY_BIN/$SCRIPT_NAME" << SCRIPT
#!/bin/bash
# Auto-generated by omarchy-zen installer
# https://github.com/mehexi/omarchy-zen

COLORS_TOML="\$HOME/.config/omarchy/current/theme/colors.toml"
ZEN_CHROME_DIR="${ZEN_CHROME_DIR}"
USERCHROMECSS="\$ZEN_CHROME_DIR/userChrome.css"

if [[ ! -d "\$ZEN_CHROME_DIR" ]]; then echo "✗ Zen profile not found at \$ZEN_CHROME_DIR"; exit 1; fi
if [[ ! -f "\$COLORS_TOML" ]]; then echo "✗ omarchy colors.toml not found"; exit 1; fi

parse_color() { grep "^\$1 " "\$COLORS_TOML" | sed 's/.*= *"\(.*\)"/\1/'; }

BG=\$(parse_color "background")
FG=\$(parse_color "foreground")
ACCENT=\$(parse_color "accent")
COLOR0=\$(parse_color "color0")
COLOR1=\$(parse_color "color1")
COLOR2=\$(parse_color "color2")
COLOR8=\$(parse_color "color8")
[[ -z "\$ACCENT" ]] && ACCENT=\$(parse_color "color4")
[[ -z "\$ACCENT" ]] && ACCENT="#89b4fa"

cat > "\$USERCHROMECSS" << EOF
/* Auto-generated by omarchy-zen — do not edit manually */
/* Theme: \$(cat \$HOME/.config/omarchy/current/theme.name 2>/dev/null || echo unknown) */

:root {
  --omarchy-bg: \${BG};
  --omarchy-fg: \${FG};
  --omarchy-accent: \${ACCENT};
  --omarchy-surface: \${COLOR0};
  --omarchy-surface-bright: \${COLOR8};
  --omarchy-red: \${COLOR1};
  --omarchy-green: \${COLOR2};

  /* Override Zen's own theme variables */
  --zen-accent-color: \${ACCENT} !important;
  --zen-border-color: \${COLOR0} !important;
  --zen-themed-toolbar-color: \${BG} !important;
  --zen-colors-primary: \${ACCENT} !important;
  --zen-colors-secondary: \${COLOR0} !important;
  --zen-colors-tertiary: \${BG} !important;
  --zen-dialog-background: \${BG} !important;
  --zen-primary-color: \${ACCENT} !important;
}

/* ── Tab bar ── */
#TabsToolbar { background-color: var(--omarchy-bg) !important; }
.tabbrowser-tab .tab-background { background-color: transparent !important; }
.tabbrowser-tab[selected] .tab-background { background-color: var(--omarchy-surface) !important; border-radius: 8px !important; }
.tabbrowser-tab .tab-label { color: var(--omarchy-fg) !important; opacity: 0.6; }
.tabbrowser-tab[selected] .tab-label { color: var(--omarchy-fg) !important; opacity: 1; }

/* ── Toolbar / URL bar ── */
#nav-bar, #PersonalToolbar { background-color: var(--omarchy-bg) !important; border: none !important; }
#urlbar-background { background-color: var(--omarchy-surface) !important; border: 1px solid var(--omarchy-surface-bright) !important; border-radius: 8px !important; }
#urlbar:focus-within #urlbar-background { border-color: var(--omarchy-accent) !important; }
#urlbar .urlbar-input { color: var(--omarchy-fg) !important; }

/* ── URL bar dropdown ── */
.urlbarView-row[selected] .urlbarView-row-inner,
.urlbarView-row[selected] { background-color: var(--omarchy-accent) !important; color: var(--omarchy-bg) !important; }
.urlbarView-row[selected] .urlbarView-title,
.urlbarView-row[selected] .urlbarView-url,
.urlbarView-row[selected] .urlbarView-secondary-action { color: var(--omarchy-bg) !important; }

/* ── Zen sidebar ── */
#zen-sidebar-container, #zen-appcontent-navbar-container { background-color: var(--omarchy-bg) !important; }
#zen-main-app-wrapper, #zen-sidebar-top-buttons, .zen-sidebar-panel-wrapper { background-color: var(--omarchy-bg) !important; }
browser, #tabbrowser-tabpanels, .browserStack { background-color: var(--omarchy-bg) !important; }

/* ── Splitter / separator ── */
#zen-sidebar-splitter, #appcontent-splitter, .zen-sidebar-splitter { background-color: var(--omarchy-surface) !important; border: none !important; min-width: 1px !important; width: 1px !important; }

/* ── Borders & titlebar ── */
#main-window { border: 1px solid var(--omarchy-surface) !important; outline: none !important; }
#zen-appcontent-navbar-wrapper { border: none !important; outline: none !important; box-shadow: none !important; background-color: var(--omarchy-bg) !important; }
#titlebar { border: none !important; outline: none !important; box-shadow: none !important; background-color: var(--omarchy-bg) !important; }
.titlebar-buttonbox-container, .titlebar-buttonbox { border: none !important; outline: none !important; box-shadow: none !important; background: transparent !important; }
.titlebar-button { border: none !important; box-shadow: none !important; }
EOF

echo "✓ Zen theme updated → \$USERCHROMECSS"

# Restart Zen to apply
if pgrep -x zen > /dev/null; then
  pkill zen; sleep 1; /opt/zen-browser/zen &
fi
SCRIPT

chmod +x "$OMARCHY_BIN/$SCRIPT_NAME"
echo "✓ Installed $SCRIPT_NAME to $OMARCHY_BIN"

# ── 4. Hook into omarchy-theme-set-browser ────────────────────────────────────
BROWSER_SCRIPT="$OMARCHY_BIN/omarchy-theme-set-browser"
if ! grep -q "omarchy-theme-set-zen" "$BROWSER_SCRIPT" 2>/dev/null; then
  echo -e "\n# Apply theme to Zen Browser\nomarchy-theme-set-zen" >> "$BROWSER_SCRIPT"
  echo "✓ Hooked into omarchy-theme-set-browser"
else
  echo "✓ Hook already present in omarchy-theme-set-browser"
fi

# ── 5. Apply current theme ────────────────────────────────────────────────────
echo "→ Applying current theme..."
"$OMARCHY_BIN/$SCRIPT_NAME"

echo ""
echo "✓ omarchy-zen installed successfully!"
echo ""
echo "  Zen will now update automatically when you switch omarchy themes."
echo "  To manually apply: omarchy-theme-set-zen"
echo ""
echo "  Note: Make sure toolkit.legacyUserProfileCustomizations.stylesheets"
echo "  is set to true in Zen's about:config"
